### ISSUE TITLE
Unable to add wlan0 to bridge

### ISSUE THREAD

**Issue by ctuffli** [chyves/chyves#14]
Adapting one of the setup steps shown in the video doesn't seem to work:

```
[root@chuck-laptop] ~# ifconfig -l
em0 lo0 wlan0
[root@chuck-laptop] ~# chyves network bridge0 attach wlan0
Critical error detected. Exiting for following reason:
Invalid interface given: 'wlan0'.
```

The BUG_REPORTS.md mentions the command `chyves debug`, but the version available in ports doesn't seem to support this command:

```
[root@chuck-laptop] ~# chyves debug
Critical error detected. Exiting for following reason:
Invalid guest name debug supplied.
[root@chuck-laptop] ~# chyves help
chyves v0.2.0 2016/09/11
chyves branch: 'master'
chyves dataset version: 0005
chyves guest version: 0300
On FreeBSD 12.0-CURRENT
FreeBSD commit: r
FreeBSD version revision: 1200012
```

**Comment by EpiJunkie** [comment]
@ctuffli, unfortunately wireless devices are unable to be added as physical interface for chyves due to the way bhyve works. As an alternative, you can NAT the wireless interface after making the bridge private in chyves with `chyves network bridge0 private`.

Excerpt from [the bhyve FAQ](https://wiki.freebsd.org/bhyve): 

```
Q: Why can't I network VMs over a wireless host interface?

A: Access points cannot determine the destination VMs and only see the host. Consider a simple pf(4) pf.conf configuration: 

nat on wlan0 from bridge0:network to any -> (bridge0)
pass out all
pass in all
```

Also thank you for bringing to my attention the error in documentation. I have not yet written the `debug` sub-command and will remove it for now.

**Comment by ctuffli** [comment]
OK, thanks for the pointer.

**Comment by weeclemans** [comment]
Hello.
I have a similar problem.



```
# ifconfig -l
igb0 igb1 lo0 bridge0 ue0 tap50 tap0 tap51 bridge1
# chyves network bridge1 attach ue0
Critical error detected. Exiting for following reason:
 Invalid interface given: 'ue0'.
```



What do I wrong ?

**Comment by EpiJunkie** [comment]
`ue0` is a wireless device and is unsupported to be added as a physical interface within chyves or bhyve.
